### ISSUE TITLE
Latest commit may contain bugs as IntelliJ refactor changed "name" to "names"

### ISSUE THREAD

**Issue by Shad0wCore** [Open-Cloud-Services/Open-Cloud#23]
The latest commit "https://github.com/Open-Cloud-Services/Open-Cloud/commit/bb0cad4153df0e8ab19524d2e23c93dccc1656a6" may lead to bugs as the Intellij refactor engine may have potentially renamed multiple text occurrences of "name" to "names" unwillingly.

Such bug can be found here: https://github.com/Open-Cloud-Services/Open-Cloud/commit/bb0cad4153df0e8ab19524d2e23c93dccc1656a6#diff-290502080bc38e8b5672986a2ded13e8R24

I could be wrong but I think this wasn't supposed to happen at all.

**Comment by Tammo0987** [comment]
Yeah you right, i will fix that
